server:
  port: 80

spring:
  application:
    name: cloud-consumer-hystrix-gloub-order
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka