
server:
  port: 9901

spring:
  application:
    name: cloudalibaba-sentinel-provider
  cloud:
    nacos:
      discovery:
        #Nacos服务注册中心地址（改成自己的服务器ip地址，本地用localhost‍）
        server-addr: localhost:8848
    sentinel:
      transport:
        #配置Sentinel dashboard地址（改成自己的服务器ip地址，本地用localhost‍）
        dashboard: localhost:8080
        # 默认8719端口，假如被占用了会自动从8719端口+1进行扫描，直到找到未被占用的 端口
        port: 8719
        client-ip: 127.0.0.1


#暴露监控的端点
management:
  endpoints:
    web:
      exposure:
        include: '*'