server:
  port: 9002


spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #配置的Nacos地址（本机的写localhost:8848，服务器的写IP地址）


management:
  endpoints:
    web:
      exposure:
        include: '*'
